services:
#  yugabytedb-extension:
#    image: ${DESKTOP_PLUGIN_IMAGE}

  yugabytedb:
    image: docker.io/yugabytedb/yugabyte:latest
    hostname: yb1
    command: |
     bash -c "
     bin/yugabyted start --listen yb1 --daemon=false --tserver_flags='ysql_enable_auth=true'
     "
    ports:
      - 5433:5433
      - 7000:7000
